server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycf?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: none

  redis:
    port: 6379
    host: 39.99.193.207
    database: 0

  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /img/**


  resources:
    static-locations: file:D:\\upload\





mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

logging.level.org.springframework.boot.autoconfigure: info
debug: off